service: project-forgetmenot-backend
provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  
functions:
  bills:
    handler: bills.handler
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}

    events:
      - http:
          method: get
          path: bills
          cors: true

      - http:
          method: post
          path: bills
          cors: true

      - http:
          method: delete
          path: bills/{billId}
          cors: true
          
      - http:
          method: put
          path: bills/{billId}
          cors: true
      
      - http:
          method: get
          path: bills/reminders
          cors: true

  reminder:
    handler: reminder.handler
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - schedule: rate(2 minutes)
